M48
; DRILL file KiCad 10.0.3 date 2026-07-19T19:03:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-19T19:03:08+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X77.655Y-81.925
X83.435Y-81.925
T2
X90.0Y-91.0
X102.74Y-120.5
M30
